@ NOTE: The brailleformat macro in this file is leftover from RS.
@       The numbers are simply skipped over. If you'd like to omit
@       this macro you must also stop it from skipping over this
@       section by editing ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "Go Up Here.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Abc$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Ghi$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Mno$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Tuv$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Def$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Jkl$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Pqrs$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "Wxyz$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "Dig Here.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "First Comes\n"
	.braille "Wailord.\n"
	.braille "Last Comes\n"
	.braille "Relicanth.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "In This\n"
	.braille "Cave We\n"
	.braille "Have\n"
	.braille "Lived.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "We Owe All\n"
	.braille "To The\n"
	.braille "Pokemon.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "But, We\n"
	.braille "Sealed The\n"
	.braille "Pokemon\n"
	.braille "Away.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "We Feared It.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "Those With\n"
	.braille "Courage,\n"
	.braille "Those With\n"
	.braille "Hope.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "Open A Door.\n"
	.braille "An Eternal\n"
	.braille "Pokemon\n"
	.braille "Waits.$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "Left, Left,\n"
	.braille "Down, Down.\n"
	.braille "Then, Use\n"
	.braille "Rock Smash.$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "Stay Close\n"
	.braille "To The Wall.\n"
	.braille "Run Around\n"
	.braille "One Lap.$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Those Who\n"
	.braille "Inherit Our\n"
	.braille "Will, Shine\n"
	.braille "In The Middle.$"

@ FRLG
Braille_Text_Up::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Up$"

Braille_Text_Down::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Down$"

Braille_Text_Right::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Right$"

Braille_Text_Left::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Left$"

Braille_Text_Cut::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Cut$"

Braille_Text_ABC::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Abc$"

Braille_Text_GHI::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Ghi$"

Braille_Text_MNO::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Mno$"

Braille_Text_TUV::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Tuv$"

Braille_Text_DEF::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Def$"

Braille_Text_JKL::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Jkl$"

Braille_Text_PQRS::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Pqrs$"

Braille_Text_WXYZ::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Wxyz$"

Braille_Text_Period::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille ".$"

Braille_Text_Comma::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille ",$"

Braille_Text_Everything::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Everything$"

Braille_Text_HasMeaning1::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Has Meaning$"

Braille_Text_Existence::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Existence$"

Braille_Text_HasMeaning2::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Has Meaning$"

Braille_Text_BeingAlive::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Being Alive$"

Braille_Text_HasMeaning3::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Has Meaning$"

Braille_Text_HaveDreams::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Have Dreams$"

Braille_Text_UsePower::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Use Power.$"

Braille_Text_LetTheTwo::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Let The Two$"

Braille_Text_Glittering::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Glittering$"

Braille_Text_Stones::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Stones$"

Braille_Text_OneInRed::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "One In Red$"

Braille_Text_OneInBlue::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "One In Blue$"

Braille_Text_ConnectThe::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Connect The$"

Braille_Text_Past::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Past.$"

Braille_Text_TwoFriends::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Two Friends$"

Braille_Text_Sharing::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Sharing$"

Braille_Text_PowerOpen::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "Power Open$"

Braille_Text_AWindowTo::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "A Window To$"

Braille_Text_ANewWorld::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "A New World$"

Braille_Text_ThatGlows::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "That Glows.$"

Braille_Text_TheNext::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "The Next$"

Braille_Text_WorldWaits::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "World Waits$"

Braille_Text_ForYou::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "For You.$"

